Downgraded libjna to 3.2.5
Crashplan 4.4.1 uses libjna 4.1.0, which causes the following error on a DroboFS:
"java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.inotify.InotifyManager"